apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-k4wx
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0072-tenant/tkrw-pr712-0075-0072-app/devfile-sample-k4wx@sha256:545d23f82116a1b7d58a170c8ef9a77f8c8059ee3cd53acb5e739581188abff4
        name: my-nodejs
        resources: {}
status: {}
